### ISSUE TITLE
Rewrite HTTP handling engine

### ISSUE THREAD

**Issue by gear54rus** [odin-public/RESTED-APS#47]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**Your envieronment**
0.0.9 Any

**What is the current behavior?**
We simply use HTML5 `fetch` to send HTTP requests and receive responses.

**What is the expected behavior?**
Use [`webRequest`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest) API instead.

The following functionality is needed:
- [ ] No automatic 401 prompt on auth failure: #15 
- [ ] Restricted request/response headers: #37 
- [ ] Better error reporting if possible (TCP, DNS?): #35
- [ ] APS Token refresh does not clear main response panel: #20

**Videos/screenshots of the issue**
N/A.
